stages:
  - test
  - deploy

before_script:
  - cd website/
  - composer install

perform_tests:
  stage: test
  script: phpunit --coverage-text

deploy_files:
  stage: deploy
  script:
    - pwd
#    - php /var/www/website/artisan down
#    - cp -r website/ /var/www
#    - cd /var/www/website
#    - composer update
#    - chgrp -R www-data .
#    - php artisan up