stages:
  - build
  - test
  - deploy

install_composer:
  stage: build
  script:
    - cd website/
    - composer install

perform_tests:
  stage: test
  script:
    - cd website/
    - phpunit --coverage-text

deploy_files:
  stage: deploy
  script:
    - php /var/www/website/artisan down
    - cp -r . /var/www
    - cd /var/www/website
    - composer update
    - chgrp -R www-data .
    - php artisan up