install_composer:
  type: build
  script:
    - cd website/
    - composer install

perform_tests:
  type: test
  script: phpunit --coverage-text

deploy_files:
  type: deploy
  script:
    - php /var/www/website/artisan down
    - cp -r . /var/www
    - cd /var/www/website
    - composer update
    - chgrp -R www-data .
    - php artisan up