stages:
- build
- release
- deploy

variables:
  RANCHER_PROJECT_NAME: Website
  RANCHER_SERVICE_NAME: web
  RANCHER_COMPOSE_VERSION: v0.8.2
  REGISTRY_URL: registry.michaeldpalmer.com
  PROJECT_PATH: michael/website
  CONTAINER_TEST_IMAGE: $REGISTRY_URL/$PROJECT_PATH:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $REGISTRY_URL/$PROJECT_PATH:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_URL

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker run --entrypoint /usr/local/bin/rancher-compose monostream/rancher-compose \
    --project-name $RANCHER_PROJECT_NAME up -d -p --force-upgrade $RANCHER_SERVICE_NAME
  only:
    - master
