stages:
  - test
  - deploy

test:
  stage: test
  except:
    - master@michael/Website
  tags:
    - docker
    - php5.6
  image: php:5.6
  script:
    - wget https://phar.phpunit.de/phpunit.phar
    - php phpunit.phar --coverage-text --colors=never
  artifacts:
    paths:
      - phpunit.xml

deploy:
  stage: deploy
  only:
    - master@michael/Website
  tags:
    - web
  script:
    - docker build -t michaelpalmer/web .
    - if [ ! -z "$(docker ps | grep web)" ]; then docker stop web; fi
    - if [ ! -z "$(docker ps -a | grep web)" ]; then docker rm web; fi
    - docker run -d -e VIRTUAL_HOST=michaeldpalmer.com --name web --restart always michaelpalmer/web