stages:
- build
- release
- deploy

variables:
  RANCHER_PROJECT_NAME: Website
  RANCHER_SERVICE_NAME: web
  RANCHER_COMPOSE_VERSION: v0.8.2
  REGISTRY_URL: registry.michaeldpalmer.com
  PROJECT_PATH: michael/website
  CONTAINER_TEST_IMAGE: $REGISTRY_URL/$PROJECT_PATH:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $REGISTRY_URL/$PROJECT_PATH:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_URL

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  script:
    - apt-get update -q
    - apt-get install -y -q --no-install-recommends ca-certificates tar wget
    - wget -O /tmp/rancher-compose-linux-amd64-${RANCHER_COMPOSE_VERSION}.tar.gz "https://github.com/rancher/rancher-compose/releases/download/${RANCHER_COMPOSE_VERSION}/rancher-compose-linux-amd64-${RANCHER_COMPOSE_VERSION}.tar.gz"
    - tar -xf /tmp/rancher-compose-linux-amd64-${RANCHER_COMPOSE_VERSION}.tar.gz -C /tmp
    - mv /tmp/rancher-compose-${RANCHER_COMPOSE_VERSION}/rancher-compose /usr/local/bin/rancher-compose
    - chmod +x /usr/local/bin/rancher-compose
    - rancher-compose --project-name $RANCHER_PROJECT_NAME up -d -p --force-upgrade $RANCHER_SERVICE_NAME
  only:
    - master
