stages:
  - test
  - deploy

before_script:
  - cd website/
  - composer install

perform_tests:
  stage: test
  script: phpunit --coverage-text

deploy_files:
  stage: deploy
  script:
    - php /var/www/website/artisan down
    - sudo cp -r . /var/www/website
    - cd /var/www/website
    - composer update
    - php artisan up
    - sudo chown -R www-data:www-data /var/www/website