stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master@michael/Website
  tags:
    - web
  script:
    - docker build -t michaelpalmer/dockers:web .
    - docker push michaelpalmer/dockers:web
    - rancher-compose up -d -p --upgrade web
