stages:
  - test
  - deploy

before_script:
  - cd html/
  - composer install

perform_tests:
  stage: test
  script: phpunit --coverage-text --colors=never

deploy_files:
  stage: deploy
  only:
    - master@michael/Website
  script:
    - echo $RUNNER_PW | sudo -S cp -r . /var/www/html
    - cd /var/www/html
    - composer update
    - sudo -S chown -R www-data:www-data /var/www/html