before_script:
  - echo $CI_PROJECT_DIR
  - BUILD_DIR = `pwd`

deploy_files:
  type: deploy
  script:
    - echo $BUILD_DIR
#    - cp -r website /var/www
#    - chgrp -R www-data /var/www/website/*
#    - cd /var/www/website
#    - composer install