stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master@michael/Website
  tags:
    - web
  script:
    - docker build -t michaelpalmer/dockers:web .
    - docker push michaelpalmer/dockers:web
    - rancher-compose upgrade web
#    - docker run -d -e VIRTUAL_HOST=michaeldpalmer.com --name web --restart always michaelpalmer/web