web:
  environment:
    VIRTUAL_HOST: www.michaeldpalmer.com,michaeldpalmer.com
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: host=aws
  tty: true
  image: michaelpalmer/dockers:web
  stdin_open: true
